---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'linux-headers-{{ wireguard__headers_map[ansible_machine] }}'
    - 'wireguard-dkms'
    - 'wireguard-tools'

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
