---

- name: install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - 'linux-headers-{{ wireguard__headers_map[ansible_machine] }}'
    - 'wireguard-dkms'
    - 'wireguard-tools'

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: add fact real ip
  template:
    src: etc/ansible/facts.d/real_ip.fact.j2
    dest: /etc/ansible/facts.d/real_ip.fact
    owner: root
    group: root
    mode: 0755
  register: wireguard__register_facts

- name: Update Ansible facts if they were modified
  action: setup
  when: wireguard__register_facts|changed

## vim: foldmethod=marker:tabstop=2:shiftwidth=2:softtabstop=2
